build_from:
  aarch64: "ghcr.io/home-assistant/aarch64-base:3.15"
  amd64: "ghcr.io/home-assistant/amd64-base:3.15"
labels:
  org.opencontainers.image.title: "Home Assistant Java Add-on"
  org.opencontainers.image.description: "Home Assistant add-on for Java."
  org.opencontainers.image.source: "https://github.com/andrei-vss/home-assistant-java-addon"
  org.opencontainers.image.licenses: "Apache License 2.0"
args:
  TEMPIO_VERSION: "2021.09.0"
